apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-echo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-echo
  template:
    metadata:
      labels:
        app: http-echo
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo
        args: ["-text", "woof"]
        ports:
          - containerPort: 5678

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: http-echo-service
  name: http-echo-service
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 80 # The port that this service should listen on.
      targetPort: 5678 # The container port that this service should forward to.
      protocol: TCP
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
    app: http-echo

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: http-echo-ingress
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - rangerdanger.dev
    secretName: rangerdanger-dev-https-cert
  rules:
  - host: rangerdanger.dev
    http:
      paths:
      - backend:
          serviceName: http-echo-service
          servicePort: 80
        path: /
